exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "vendor", "Gemfile", "Gemfile.lock", "Guardfile", "assets.yml"]
highlighter: pygments


exclude_from_localizations: ["javascript", "images", "css"]

title: Hi, I'm Christina Xu.
description: I'm an organizational designer and ethnographer based in New York.
url: http://www.christinaxu.org
permalink: /:categories/:title
production_url: http://www.christinaxu.org
contact_email: hey@christinaxu.org

sass:
  style: :compressed
  sass_dir: assets/stylesheets

google_analytics: todo
google_site_verification: todo

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "smart"]

collections:
  seminars:
    output: true
  books:
    output: true
